services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=gogocash
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gogocash"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gogocash-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - gogocash-network

volumes:
  postgres_data:

networks:
  gogocash-network:
    driver: bridge
